### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by mayuxi987** [Nashex/gpt4-playground#24]
Hi, I am grateful for the tool because I share my account with others. This allows me to use GPT via API, which is extremely helpful. But since yesterday, I could not be able to use it. The error goes: Unexpected end of JSON input.

Thanks for solving the issue.

**Comment by Nashex** [comment]
Should be fixed!

**Comment by mayuxi987** [comment]
Thanks!! It works!!
