### ISSUE TITLE
Please bring back the ability to delete messages

### ISSUE THREAD

**Issue by dikiyvaper228** [Nashex/gpt4-playground#3]
![image](https://user-images.githubusercontent.com/125809794/229266052-b1fce460-b32e-43b5-b278-36c537446d33.png)
20 minutes ago there was a cross with which you could delete an unnecessary message, but now apparently nothing at all. And as I understand it, after each update, my chat history disappears

**Comment by Nashex** [comment]
Sorry about the history, that was only for the one update white I refactored it to follow a more open-closed style. This PR should resolve those bugs!
